atr_multiplier: 1.8
atr_period: 9
batch_size: 256
confidence_threshold: 0.27
data_path: xau
enabled_symbols:
- $USDX
- USDJPY
- XAUUSD
epochs: 144
feature_symbols:
  $USDX: true
  ADAUSD: false
  AVAXUSD: false
  AXSUSD: false
  BCHUSD: false
  BTCUSD: false
  DOGEUSD: false
  DOTUSD: false
  EOSUSD: false
  ETHUSD: false
  FILUSD: false
  LINKUSD: false
  LTCUSD: false
  MATICUSD: false
  MIOTAUSD: false
  SOLUSD: false
  TRXUSD: false
  UNIUSD: false
  USDJPY: true
  XAUUSD: true
  XLMUSD: false
  XRPUSD: false
features:
  adx:
    enabled: true
    periods:
    - 9
  bollinger:
    enabled: true
    periods:
    - 9
    std: 2.0
  candle_ratios:
    enabled: true
  ema_cross:
    enabled: true
    pairs:
    - - 9
      - 18
  garman_klass:
    enabled: true
    windows:
    - 5
  higher_timeframes:
    enabled: true
    log_return_periods:
    - 1
    macd:
      fast: 12
      signal: 9
      slow: 26
    rsi_periods:
    - 9
    timeframes:
    - 9
  log_returns:
    enabled: true
    periods:
    - 1
    - 5
  macd:
    enabled: true
    fast: 3
    signal: 9
    slow: 6
  price_to_ema:
    enabled: true
    periods:
    - 5
  price_to_sma:
    enabled: true
    periods:
    - 15
  rolling_volatility:
    enabled: true
    windows:
    - 5
  rsi:
    enabled: true
    periods:
    - 3
    - 6
    - 9
  tick_volume:
    enabled: true
    timeframes:
    - 15
    - 60
  time:
    day_of_week: true
    enabled: true
    hour: true
    minute: true
hidden_size: 100
input_dim: 86
learning_rate: 1.0e-05
model_output: model.onnx
n_ahead: 54
norm_output: norm_params.mqh
seed: 42
sequence_length: 54
stop_loss_pct: 0.5
sub_dim: 20
symbol: XAUUSD
target_type: atr
threshold_pct: 1.0
tp_multiplier: 1.44
train_test_split: 0.8
