# Symbol
symbol: "XAUUSD"

# Symbol
target_type: "atr"
atr_multiplier: 1.8
tp_multiplier: 1.44
atr_period: 9
confidence_threshold: 0.27

# Data
data_path: "xau"
sequence_length: 54
n_ahead: 54

feature_symbols:
  $USDX: true
  USDJPY: true
  BCHUSD: false
  BTCUSD: false
  ETHUSD: false
  LTCUSD: false
  XRPUSD: false
  ADAUSD: false
  AVAXUSD: false
  AXSUSD: false
  DOGEUSD: false
  DOTUSD: false
  EOSUSD: false
  FILUSD: false
  LINKUSD: false
  MATICUSD: false
  MIOTAUSD: false
  SOLUSD: false
  TRXUSD: false
  UNIUSD: false
  XLMUSD: false

features:
  log_returns:
    enabled: true
    periods: [1, 5]
  candle_ratios:
    enabled: true
  garman_klass:
    enabled: true
    windows: [5]
  rolling_volatility:
    enabled: true
    windows: [5]
  bollinger:
    enabled: true
    periods: [9]
    std: 2.0
  price_to_sma:
    enabled: true
    periods: [15]
  price_to_ema:
    enabled: true
    periods: [5]
  ema_cross:
    enabled: true
    pairs:
      - [9, 18]
  rsi:
    enabled: true
    periods: [3, 6, 9]
  adx:
    enabled: true
    periods: [9]
  macd:
    enabled: true
    fast: 3
    slow: 6
    signal: 9
  higher_timeframes:
    enabled: true
    timeframes: [9]
    log_return_periods: [1]
    rsi_periods: [9]
    macd:
      fast: 12
      slow: 26
      signal: 9
  time:
    enabled: true
    hour: true
    minute: true
    day_of_week: true

# Labels
threshold_pct: 1.0
stop_loss_pct: 0.5

# Model
hidden_size: 100
sub_dim: 20

# Training
batch_size: 256
learning_rate: 0.00001
epochs: 144
train_test_split: 0.8
seed: 42

# Output
model_output: "model.onnx"
norm_output: "norm_params.mqh"