const string SYMBOLS[] = {
   "BCHUSD","BTCUSD","ETHUSD","LTCUSD","XRPUSD","ADAUSD","AVAXUSD","AXSUSD","DOGEUSD","DOTUSD",
   "EOSUSD","FILUSD","LINKUSD","MATICUSD","MIOTAUSD","SOLUSD","TRXUSD","UNIUSD","XLMUSD"
};